import"./assets/modulepreload-polyfill-B5Qt9EMX.js";import"./assets/api-service-2-Do44Dpm1.js";let n=1,r=0;const d=document.querySelector(".movie-grid"),u=document.getElementById("prev-btn"),g=document.getElementById("next-btn"),c=document.querySelector(".page-numbers"),v="8a4d9ed67b7d6af3412d8460b7ed63ee";let y={};async function E(){try{y=(await(await fetch(`https://api.themoviedb.org/3/genre/movie/list?api_key=${v}&language=en-US`)).json()).genres.reduce((o,a)=>(o[a.id]=a.name,o),{})}catch(e){console.error("Error fetching genres:",e)}}async function i(e=1){try{const o=await(await fetch(`https://api.themoviedb.org/3/trending/movie/week?api_key=${v}&page=${e}`)).json();if(r=o.total_pages,!o.results||o.results.length===0){d.innerHTML='<p class="error">No movies found for this page.</p>';return}b(o.results),w(),L()}catch(t){console.error("Error fetching movies:",t),d.innerHTML='<p class="error">Movies could not be loaded. Please try again later.</p>'}}function b(e){d.innerHTML=e.map(t=>{var a;const o=(t.genre_ids||[]).map(h=>y[h]).filter(Boolean).join(", ");return`
            <div class="movie-card" data-id="${t.id}">
                <div class="movie-poster-container">
                    <img src="${t.poster_path?`https://image.tmdb.org/t/p/w500${t.poster_path}`:"path/to/placeholder.jpg"}" 
                         class="movie-poster" alt="${t.title}">
                    <div class="movie-overlay">
                        <h3 class="movie-title">${t.title}</h3>
                        <div class="movie-date-genres">
                        <p class="movie-genres">${o||"N/A"} |</p>
                        <p class="movie-release-date">${t.release_date?new Date(t.release_date).getFullYear():"N/A"}</p>
                           
                        </div>
                    </div>
                </div>
                <div class="movie-info">
                    <p class="movie-rating">⭐ ${((a=t.vote_average)==null?void 0:a.toFixed(1))||"N/A"}</p>
                </div>
            </div>
            `}).join("")}function w(){c.innerHTML="";const e=Math.max(1,n-2),t=Math.min(r,n+2);e>1&&s(1),e>2&&p();for(let o=e;o<=t;o++)s(o);t<r-1&&p(),t<r&&s(r)}function s(e){const t=document.createElement("span");t.classList.add("page"),e===n&&t.classList.add("active"),t.textContent=e,t.addEventListener("click",()=>{n!==e&&(n=e,i(n))}),c.appendChild(t)}function p(){const e=document.createElement("span");e.classList.add("dots"),e.textContent="...",c.appendChild(e)}function L(){u.disabled=n===1,g.disabled=n===r}u.addEventListener("click",()=>{n>1&&(n--,i(n))});g.addEventListener("click",()=>{n<r&&(n++,i(n))});async function B(){await E(),i(n)}B();const $="https://api.themoviedb.org/3",M="8a4d9ed67b7d6af3412d8460b7ed63ee",m=document.getElementById("movie-modal"),I=document.querySelector(".close-button"),_=document.getElementById("modal-poster"),x=document.getElementById("modal-title"),k=document.getElementById("modal-votes"),N=document.getElementById("modal-popularity"),P=document.getElementById("modal-genre"),C=document.getElementById("modal-overview"),S=document.getElementById("add-to-library");let l=null;document.addEventListener("click",async e=>{const t=e.target.closest(".movie-card");if(t){const o=t.getAttribute("data-id");if(o)try{const a=await A(o);a?T(a):console.error("Film detayları getirilemedi.")}catch(a){console.error("Film detayları alınırken hata oluştu:",a)}else console.error("Kart üzerinde geçerli bir movieId bulunamadı.")}});async function A(e){try{if(!e)throw new Error("Geçersiz film ID");const t=await fetch(`${$}/movie/${e}?api_key=${M}&language=en-US`);if(!t.ok)throw new Error(`Film detayları getirilemedi: ${t.status}`);const o=await t.json();return console.log("Movie Data:",o),o}catch(t){return console.error("Error fetching movie details:",t),null}}function T(e){var t,o;try{l=e,_.src=e.poster_path?`https://image.tmdb.org/t/p/w500${e.poster_path}`:"https://via.placeholder.com/250x350?text=No+Image",x.textContent=e.title||"No Title",k.textContent=`${((t=e.vote_average)==null?void 0:t.toFixed(1))||"N/A"} / ${e.vote_count||"0"}`,N.textContent=((o=e.popularity)==null?void 0:o.toFixed(1))||"N/A",P.textContent=e.genres?e.genres.map(a=>a.name).join(", "):"N/A",C.textContent=e.overview||"No description available.",m.classList.remove("visually-hidden"),document.body.style.overflow="hidden"}catch(a){console.error("Error opening modal:",a)}}function f(){m.classList.add("visually-hidden"),document.body.style.overflow="auto"}I.addEventListener("click",f);window.addEventListener("click",e=>{e.target===m&&f()});S.addEventListener("click",()=>{let e=JSON.parse(localStorage.getItem("library"))||[];e.some(t=>t.id===l.id)?alert("This movie is already in your library."):(e.push(l),localStorage.setItem("library",JSON.stringify(e)),alert("Movie added to library!"))});
//# sourceMappingURL=catolog.js.map
