import"./assets/modulepreload-polyfill-B5Qt9EMX.js";const c="8a4d9ed67b7d6af3412d8460b7ed63ee",d="https://api.themoviedb.org/3",w="https://image.tmdb.org/t/p/w500",u=document.getElementById("movies");document.getElementById("search-form");const l=document.getElementById("search-input"),h=document.getElementById("search-btn"),v=document.getElementById("membership");let p=null;async function f(t="",e=""){t===""&&e===""?await y(`${d}/movie/popular?api_key=${c}&language=en-US&page=1`):e!==""&&t===""?await L(e):await $(t,e)}async function L(t){try{const e=`${d}/discover/movie?api_key=${c}&language=en-US&primary_release_year=${t}&sort_by=popularity.desc&page=1`,o=await(await fetch(e)).json();g(o.results)}catch(e){console.error("Error fetching movies by year:",e)}}async function $(t,e=""){try{let n=`${d}/search/movie?api_key=${c}&language=en-US&query=${t}`;e&&(n+=`&primary_release_year=${e}`);const r=await(await fetch(n)).json();g(r.results)}catch(n){console.error("Error searching movies:",n)}}h&&h.addEventListener("click",async t=>{t.preventDefault();const e=l.value.trim(),n=v.value.trim();await f(e,n)});l&&l.addEventListener("keydown",t=>{if(t.key==="Enter"){t.preventDefault();const e=l.value.trim(),n=v.value.trim();f(e,n)}});async function b(){try{const e=await(await fetch(`${d}/discover/movie?api_key=${c}&language=en-US&sort_by=popularity.desc`)).json(),n=Math.floor(Math.random()*e.results.length),o=e.results[n];_(o)}catch(t){console.error("Film verisi alınırken bir hata oluştu:",t)}}function E(t){const e=document.createElement("div");e.classList.add("star-rating");const n=t/2,o=Math.floor(n),r=n%1>=.5?1:0,i=5-o-r;for(let a=0;a<o;a++){const s=document.createElement("span");s.classList.add("star","full"),s.innerHTML="★",e.appendChild(s)}if(r){const a=document.createElement("span");a.classList.add("star","half"),a.innerHTML="☆",e.appendChild(a)}for(let a=0;a<i;a++){const s=document.createElement("span");s.classList.add("star","empty"),s.innerHTML="☆",e.appendChild(s)}return e}function _(t){const e=document.querySelector(".hero-title");e.textContent=t.title;const n=document.querySelector(".hero");n.style.backgroundImage=`url(https://image.tmdb.org/t/p/original/${t.backdrop_path||""})`;const o=document.querySelector(".hero-description");o.textContent=t.overview||"Bu film için açıklama mevcut değil.";const r=document.querySelector(".more-details-btn");r.href=`https://www.themoviedb.org/movie/${t.id}`;const i=document.querySelector(".hero-rating");i.innerHTML="",i.appendChild(E(t.vote_average||0))}async function y(t){try{const n=await(await fetch(t)).json();g(n.results)}catch(e){console.error("Error fetching movies:",e)}}async function g(t){if(u.innerHTML="",t.length===0)u.innerHTML="<p>No movies found.</p>";else for(let e of t){const{title:n,poster_path:o,vote_average:r,release_date:i,genre_ids:a}=e,k=(a?await Promise.all(a.map(M=>S(M))):[]).join(", ")||"N/A",m=document.createElement("div");m.classList.add("movie-card"),m.innerHTML=`
                <div class="movie-poster-container">
                    <img 
                        class="movie-poster" 
                        src="${o?w+o:"https://via.placeholder.com/200x300?text=No+Image"}" 
                        alt="${n}" 
                    />
                    <div class="movie-overlay">
                        <h3 class="movie-title">${n}</h3>
                        <p class="movie-release-date">${i?new Date(i).getFullYear():"N/A"}</p>
                        <p class="movie-genres">${k}</p>
                    </div>
                </div>
                <div class="movie-info">
                    <p class="movie-rating">⭐ ${r.toFixed(1)}</p>
                </div>
            `,u.appendChild(m)}}async function S(t){p||(p=(await(await fetch(`${d}/genre/movie/list?api_key=${c}&language=en-US`)).json()).genres);const e=p.find(n=>n.id===t);return e?e.name:"Unknown"}function B(){const e=document.body.classList.toggle("dark-mode");localStorage.setItem("darkMode",e?"enabled":"disabled")}document.addEventListener("DOMContentLoaded",()=>{localStorage.getItem("darkMode")==="enabled"&&document.body.classList.add("dark-mode");const e=document.querySelector(".toggle-dark-mode");e&&e.addEventListener("click",B),b(),y(`${d}/movie/popular?api_key=${c}&language=en-US&page=1`)});
//# sourceMappingURL=catolog.js.map
